### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Warlib1975** [schlingensiepen/TelegramBotClient#5]
I upload the example ESP_EchoBot.ino on the ESP8266 (Wemos D1 mini board), but it doesn't work. Wifi connection works ok, but messages from the telegram chatbot don't arrive. No any errors, just nothing. :-(

**Comment by joern-schlingensiepen** [comment]
Dear Warlib1975,

thanks for your report, could you explain, how we could help you, while you do not provide any information about what you did and how your code looks like?

Best Regards
